travis:
  secure:
    BINSTAR_TOKEN: cgsfvAVBHSNfKlOCm+XkjnT1qC15CXttjWVxcrQeU/hJuya/ioHJXIHjM5y00DH0dFWNptw3JcNa7B8W/VCwgcZhQ2lQ+sVuYOnEezu0rgzUwJ5MEW30eAddzZnOOUNCvnv4YCdGtLSyhwrWGFlqfzVgfXMU/D5DLosN9wNpWc5cFVIxSCTMjlMztQG6labXDiqx2hLPBi2tHfIiZLyYBSMod2VvPk9XY5zKMcenDXa5WCglazgO69nvHGWCgJGOZ7OWEfB0XCVO8G0RoiglqU/P8Q+xKOD2ih3dCjL0Q/7cm2vGm77YJVzq5tBBT+LmNM1bQB3ZDjmVy/R1V7Uv2uYZjFLavNJddd2h12jbaHq4Fk+tt47kQ7Y1Rx2Rwh/er+PaIiSuFgmOCp0L06F2rB7aqvTjkX63I7fwUfUCqeGCtDV+I/HQYp2wlhsBUjodqxItmMq7MffDmCR0xG9WrYYvU7LHorqgUCV5lJrDU+ZT+qtxM4f808+HcFM+CO0XbQo70QzgDEjqeaVFYW2VBVfN4iEOyzpeN/nrZRe57gLZDW3U2sVjE6QVkv7dFleYD/q1sA7qQRMLqkla74/81TZcd2FRJzUbMLEMwP8PrFfcwlkSO7ylMkMqg/JQOI+sOtalmvPdgqp5zwbfgVZIvRyk/gqVoIG4B31eJhuIiYI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
