travis:
  secure:
    BINSTAR_TOKEN: E4j3t+M1xZHtg5FsqFC69TRYCttqfEjhzYayFyjum6qKOVLS8XV+FuJ9d5z5vRoHEzVZGqIe+OTYCFX95So9WvvxAqgp+XHUPmdA2FBpc4UeVdt0Bctu0QXV7F3lNHCS6+OrELCksiHWkOd7jDWTsAtyolEiF0W8Z9xTXr+YPsJRXRmVvarzUsCoDJaZXIhSBepy109MQSCrg8REY7LNepGbKghVuALAu76LtUyuDXpuZYhnh7FKYDZ+laQZrVwu7ezL0rlFPMC883BvWzc0kIwI+vgVXOZB6A66CvjHfetCtXQckRiS9iF0QYJYKfJf2T6geQFa8kbC1nSNX3sHscjKKaHg2ItFWKeOLLsG5E0XbsnnBouV75LgT3S6QBTZ0jsF21weFJDHdN7V3WrOfLG+T6npBMJYLiBL19n64iSElqWUTejBamwagXCsFNTW0lkf4iU3axv5hHH2nhelQ/bMtDkhFFSk2o9zYMG1Fwr/Et9THM56P4wgjUj0WfK0Jjr2AxPRBrtKVRNhrzRQRGqZUJFJ3YI4nedsrRct7wSwAEK/3KRdmzaJ0e6PPvuG3REP0NfWFK9t4afdWOmQ44++R43PBf/EJFcbxdjKGnCdndja3nTL7JBbnjoN7p3gbOfuelNsYxVJ2dOu2R6Sq0el7HH+ybjixy9qqcDsqb0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
