travis:
  secure:
    BINSTAR_TOKEN: aHLdfeSwoc7NdwpkGG5H4uEsnO+JkMRCXb8OZ/4N5NDzOEuO+U3LYKGnLkTPOlzNN7YkkZU3xGjKypb1YHXmHX2/pH3LFHFCQoitqKP67A5Wwu1ezMfx3VZbVOSHWvqnDSiuBHklorV5nyHbjXEojLC/WTh9n5eBHyEeu4ngREJSvj4qMR+KDXLvu3b0xWD4yXUpIbcDZqfp5Zhatt3MR8ivGt2d62Z96E+tG5gf/wxCnKOIguDBoUPKC13Ia81O0CFcYuBFNNeEMFYaRw5D92AGdU82l07+erhe3CY861o/cah7ac6cjQoRIE4CJMzFIoBROSF5ZARF1wjsLJtOd25Q0BuMl0HD6RUWi//f5JCEAXms30KkRSA73fJMvEOVh+HLKa3cqAorsWd7017VDO6mP3dheJDHCCean6RuBRQlPH7c4jYj2exUfCgVDpoL9b5XIVnYomQkvkYDpPA8KF6IbJzdPVvSSp21oPXdczYQSn2rbcYACVZeYgC+aXPQY+0Nd7XVnT3uSUC2ABFAjOEz//NxgvlOHLSLErwiBct9JoPfzsuhGnGBAj8KVXCALCeaVuDaPRqb/8fMuO98DevzO3jEjSUQsHs06lr0nfdhNrICL+rEUyaMnk7ZKUqZGqe7NVL7CRvwlX579k/8sviRrKV9jXDCr3rGzqdM1HM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
